# Generated by Django 2.0.2 on 2018-06-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20180623_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonmodel',
            name='total_episodes',
            field=models.IntegerField(default=0),
        ),
    ]
