# Generated by Django 2.0.4 on 2018-06-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0003_seasonmodel_total_episodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedseriesmodel',
            name='current_episode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addedseriesmodel',
            name='current_season',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='addedseriesmodel',
            name='personal_rating',
            field=models.IntegerField(default=0),
        ),
    ]
