# Generated by Django 2.0.4 on 2018-06-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20180625_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedseriesmodel',
            name='current_episode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='addedseriesmodel',
            name='current_season',
            field=models.IntegerField(default=1),
        ),
    ]
