# Generated by Django 2.0.2 on 2018-06-24 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profilemodel_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='date_registered',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 24, 15, 45, 27, 258766)),
        ),
    ]
